[TP-1454] Fix channel missing attributes (#176)
### Why
```
FAILED tests/client/test_collaborators.py::test_list_collaborators_with_pat - AttributeError: 'GRPCJSONChannel' object has no attribute 'unary_stream'
```

### How
* To quickly fix this, add the missing methods and mark them as not implemented. This will allow the channel to be initialised without breaking.