[LT-5283] Fix setting authorization for SDH urls (#181)
### Why
* Previous commit 22b717e70c651c87a9a8641149489157d3c11f5f did not set the headers as expected, which caused ` AttributeError: 'tuple' object has no attribute 'items'` error

#### How
* Set headers in a map instead of a list